apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ab
spec:
  ingressClassName: ingress-nginx-public
  rules:
  - host: apps.henrq.tk
    http:
      paths:
      - path: /appa
        pathType: ImplementationSpecific
        backend:
          service:
            name: app-a-service
            port:
              number: 80

      - path: /appb 
        pathType: ImplementationSpecific
        backend:
          service:
            name: app-b-service
            port:
              number: 80
